### ISSUE TITLE
More options for styling of highlighted parts

### ISSUE THREAD

**Issue by hkot1991** [cognitedata/reveal#2268]
Is there any possibility for changing the stroke width for a highlighted part?
Also is there a possibility for setting the color used to indicate that a highlighted is behind a non highlighted part? 
Thinking of the light purple/redish color here: 
![image](https://user-images.githubusercontent.com/61226854/177547746-06aed4db-b4bf-4a25-8c41-d57e3898f76d.png)

If its not possible now, then is it something that is coming or we can possibly add ourself?

**Comment by christjt** [comment]
Shortanswere is no and no. First one is relatively trivial for us to expose since we can set this internally in Reveal. The second part is a little more problematic but should also be doable. Just to make sure I understand, you want to set a different outline color for fragments that are behind opaque geometry? So an object would in essence have two different outline colors, one for what is for normal viewing and another for the parts that are behind opaque geometry?

**Comment by hkot1991** [comment]
@christjt sorry for the late reply.

Not sure I understand why the stroke with cannot be changed from a npm-package user🤔 

Yes, our issue is that we feel that the overlapp is not visibel enough for the user. I see that there is some improvments that might help there in this: https://github.com/cognitedata/reveal/pull/2248

So perhaps we will wait for this to be accessible and see if its still an issue

**Comment by christjt** [comment]
Not being able to set the stroke width is simply because we haven't exposed it. (I have added a task for it, so will try to get it in).

What I was referring to is being able to have a different outline color / stroke based on if a the outline is behind other opaque geometry or not. This is conciderably harder to do for us with our current rendering pipeline.

**Comment by hkot1991** [comment]
I will look forward to the chnage with setting the stroke width then 😄 

And I have spoken to others on my team and we understand that its hard to have different outline color based on how objects are placed. We will wait for the pr mentioned previously to be released and see if there is still the issue of it being hard for the user to see if objects are overlapping.

Thanks 👍
