### ISSUE TITLE
Loading problems while switching models

### ISSUE THREAD

**Issue by vero-so** [cognitedata/reveal#2563]
Hi! 

We have encountered some problems when trying to switching to a different model before the current model has finished loading. The error messages point to the material manager. It seems that the loaders thinks the materials are loaded and tries to fetch the material for the new model, however, they are not yet there. 

We have have discovered this issue with version 3.1.0, but tested also the latest master to see if it there also, since there were some changes with the load state -- and it is still there.

Is there a way we can go around this error? :)
Thank you
-veronika

**Comment by christjt** [comment]
Hi
Yes this is a known issue and happens due to sectors being in-flight(downloading), when a model is deleted. When the eventually get processed they try to fetch the materials for the model which does not exist anymore and will fail. Other than it being annoying, it shouldn't cause any functional issues and can be ignored.

**Comment by vero-so** [comment]
Hi again, thanks for the fast response @christjt !
Yes, when working with latest master (version 4) and V9 format, it is as you say -- just making the console reddish :)
However, version 3.1 (and V8 format), sometimes it makes the system stop working and we need to reload. Were there some changes made at some point after 3.1 so that the system keeps running despite the error?

**Comment by christjt** [comment]
Not intentionally at least. In any case, we are planning to release a patch for 3.2 (or possibly 3.3) that includes some fixes (flat modifier issue etc.). Perhaps you could try 3.2 and see if the error persists for v8?

**Comment by vero-so** [comment]
Ok, thanks. We will try that and let you know.
In any case, I have seen that LoadState has changed a bit sometime between 3.1 and 4.now :) So I hoped it might be that.

**Comment by astrid-kg** [comment]
I had another look at this, and it turns out that the loading system receives the information that model has been deleted too late and continues as if everything is normal for a while. This is handled, and the download will end once the missing model is detected, but this discovery is logged as an error.

Informing the loading sector instantly when the model is deleted is not a trivial thing to do, and since the case is handled properly we have ended on the solution to no longer log this as an error. Your problem should be fixed with this change:
https://github.com/cognitedata/reveal/pull/2957

**Comment by astrid-kg** [comment]
I had another look at this, and it turns out that the loading system receives the information that model has been deleted too late and continues as if everything is normal for a while. This is handled, and the download will end once the missing model is detected, but this discovery is logged as an error.

Informing the loading system instantly when the model is deleted is not a trivial thing to do, and since the case is handled properly we have ended on the solution to no longer log this as an error. Your problem should be fixed with this change: https://github.com/cognitedata/reveal/pull/2957
