### ISSUE TITLE
Handling the loading state of the 360 image

### ISSUE THREAD

**Issue by RodrigoRVSN** [cognitedata/reveal#4820]
Hello, Is there a way to handle the loading state of a 360 image? For example, I would like to render an overlay when I click on one of these white circles:

![image](https://github.com/user-attachments/assets/61efaab7-e8ed-440a-99b8-66ce8260e291)

The method `image360Entered` is called when the camera moves to the position of the white circle clicked, after the image is loaded. But I don't know when I start to load this 360 image, to start the loading state, with a `setIsLoading(true)` for example.

```tsx
const collection = await viewer.add360ImageSet('datamodels', {
    image360CollectionExternalId: externalId,
    space,
})
collection.on('image360Entered', () => {
    console.log('entered image')
    setIsLoading(false) // setting loading false here would mean that the image was loaded and the camera was moved to the white circle position, to show the 360 image
})
```

Also, it looks like I couldn't use the method `enter360Image` instead, that is a Promise, since it's called programmatically.

Is there a way that I can know when the 360 image starts to load, so I can set a state like `setIsLoading(true)`?

**Comment by haakonflatval-cognite** [comment]
Hi, @RodrigoRVSN ! If I understand correctly, you want to show be able to set some state e.g. in React to `true` when the user clicks a 360 icon, and then `false` once the image is done loading and the user enters the image?

It's not entirely straight-forward with the default setup for 360-images. However, there is an alternative beta feature which gives you more control of 360 handling. You can set the flag `hasEventListeners` in the `Cognite3DViewerOptions` object to `false` in the initialization of the viewer. This will prevent Reveal from explicitly handling 360-related events, including marking them on cursor hovering, entering on click, and exiting on pressing Escape.

Of course, disabling these events means you must handle them on your own. The three events above can be handled by calling `viewer.onHover360Images` on hover events, `viewer.onClick360Images` on click events, and `viewer.image360Action(Image360Action.Exit)` when the user presses Escape.

The documentation for this is rather scarce, so let me know if you need more clarification about this!

Also, since it is beta, this feature may change without warning, although I don't think it's likely to change much in the near future. I'll keep you in mind if we do decide to change it :+1: 

PS: Disabling the events will also prevent the FlexibleCameraManager from working, in case you have set the `useFlexibleCameraManager` flag in `Cognite3DViewerOptions` to true as well. Let us know, and I can give you instructions to handle that as well

**Comment by RodrigoRVSN** [comment]
> If I understand correctly, you want to show be able to set some state e.g. in React to true when the user clicks a 360 icon, and then false once the image is done loading and the user enters the image?

Yes, that's correct @haakonflatval-cognite

> You can set the flag hasEventListeners in the Cognite3DViewerOptions object to false

I tried to do it in the following way:

```tsx
const handleClick = async (event: PointerEvent) => {
    await viewer?.onClick360Images(event).then(wasHandled => {
        console.log({ wasHandled }) // returns true, but just after the camera is zoomed in the 360 image
        if (wasHandled) {
          // set is loading as true
        }
    } 
}

window.addEventListener('pointerup', handleClick)
```

The idea of this code would be to start a loading state when I click the 360 image, but the `onClick360Images` resolves when the camera is already zoomed in the 360 Image, which is triggered at the same moment as `collection.on('image360Entered')`.

I think in this case that I need to trigger a loading state before the user is being redirected to the 360 image, I would need somehow to check if a click was triggered in an element that is a 360 image, instead using this `onClick360Images`, right? I think it would be something like the `intersect360ImageIcons` method

**Comment by haakonflatval-cognite** [comment]
@RodrigoRVSN Ah, okay, I actually thought that method would resolve earlier - then I suppose you would want that `intersect360ImageIcons` method as you mentioned. It's not public right now, but I'll see if we can just make it, or a variant, public shortly :+1: 

This seems like an oversight on our part, thanks for raising it!

**Comment by haakonflatval-cognite** [comment]
@RodrigoRVSN We just released Reveal 4.21.0 which includes 360 image intersections in the result from the `viewer.getAnyIntersectionFromPixel` method (namely `Image360IconIntersection`). I believe that should solve your use case, in combination with `viewer.enter360Image`. Again, note that `getAnyIntersectionFromPixel` is in beta. We're not planning to change it, except for potentially adding more types of intersections in the return type - in any case, we'll keep you in mind if the need arises.

Let me know if you're still not able to get the intended result with the new version

Thanks again for reaching out!

**Comment by haakonflatval-cognite** [comment]
I'll mark this as closed - let me know if you disagree :+1:

**Comment by RodrigoRVSN** [comment]
I agree, I haven't tested yet but if needed I open another one, thanks for the help @haakonflatval-cognite
